name: "🐛 Report Bad Contract"
description: Report to us that certain program contract should be repaired.
title: "🐛 [TestRemoval] - <TASK_ID> <WHY>"
labels: ["program contract"]
body:
  - type: input
    id: version
    attributes:
      label: "OpenEval version"
      description: What is the version of OpenEval? You can find it by running `pip show openeval`.
      placeholder: For example, 0.1.0
    validations:
      required: true
  - type: input
    id: cache
    attributes:
      label: "Output of running `ls ~/.cache/openeval`"
    validations:
      required: true
  - type: input
    id: task_id
    attributes:
      label: "Task ID of the programming task"
      placeholder: OpenEval/[??]
    validations:
      required: true
  - type: textarea
    id: original
    attributes:
      label: "The original wrong contract"
      description: You can run `python -c "from openeval.data import get_open_eval print(get_open_eval['OpenEval/❓']['contract'])"`
      render: python
    validations:
      required: true
  - type: textarea
    id: new
    attributes:
      label: "Your proposed new contract"
      render: python
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Other context"
      description: (Optional) Anything else the maintainer should notice?
    validations:
      required: false
