# This is a config for E2B sandbox template.
# You can use template ID (tbjhnhg5e3bd22i8jqgk) or template name (bigcodebench-evaluator) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("bigcodebench-evaluator") # Sync sandbox
# sandbox = await AsyncSandbox.create("bigcodebench-evaluator") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bigcodebench-evaluator')

team_id = "f317d0d2-ba02-44c5-8b77-e4a2d7830c7c"
dockerfile = "e2b.Dockerfile"
template_name = "bigcodebench-evaluator"
template_id = "tbjhnhg5e3bd22i8jqgk"
